// Generated by CoffeeScript 1.6.3
define(["require", "jquery", "radio", "modules/turntable/turntablemodel", "modules/turntable/turntableview"], function(require, $, radio, TurntableModel, TurntableView) {
  var Turntable;
  return Turntable = (function() {
    function Turntable(_turntableClass, _eventPrefix) {
      this._turntableClass = _turntableClass != null ? _turntableClass : ".turntable";
      this._eventPrefix = _eventPrefix != null ? _eventPrefix : "TURNTABLE";
    }

    return Turntable;

  })();
});
