// Generated by CoffeeScript 1.6.3
define([], function() {
  var VoiceCancellation;
  return VoiceCancellation = (function() {
    function VoiceCancellation(_audioContext) {
      this._audioContext = _audioContext;
      this.audioProcessor = this._audioContext.createScriptProcessor(4096);
      this.audioProcessor.onaudioprocess = function(e) {
        var i, inputOne, inputTwo, outputOne, outputTwo, _i, _len, _results;
        inputOne = e.inputBuffer.getChannelData(0);
        inputTwo = e.inputBuffer.getChannelData(1);
        outputOne = e.outputBuffer.getChannelData(0);
        outputTwo = e.outputBuffer.getChannelData(1);
        _results = [];
        for (_i = 0, _len = inputOne.length; _i < _len; _i++) {
          i = inputOne[_i];
          outputOne[_i] = (inputOne[_i] - inputTwo[_i]) / 2;
          _results.push(outputTwo[_i] = (inputTwo[_i] - inputOne[_i]) / 2);
        }
        return _results;
      };
      this.audioProcessor;
    }

    return VoiceCancellation;

  })();
});
