// Generated by CoffeeScript 1.7.1
(function() {
  var config;

  config = {
    baseUrl: 'js'
  };

  require.config(config);

  requirejs(['modules/AudioMixer'], function(AudioMixer) {
    window.mixer = new AudioMixer();
    window.mixer.setAudioChannel('audio/demo.mp3', 'one');
    return window.mixer.setAudioChannel('audio/demo.mp3', 'two');
  });

}).call(this);
