// Generated by CoffeeScript 1.7.1
(function() {
  var config;

  config = {
    baseUrl: 'js'
  };

  require.config(config);

  requirejs(['modules/AudioStream'], function(AudioStream) {
    window.a = new AudioStream('audio/demo.mp3');
    return window.b = new AudioStream('audio/demo.mp3');
  });

}).call(this);
