// Generated by CoffeeScript 1.7.1
(function() {
  define(['modules/AudioLoader', 'modules/AudioFilters'], function(AudioLoader, AudioFilters) {

    /**
    	 * AudioStream makes it easy to load audio files and apply basic filters to them
     */
    var AudioStream;
    return AudioStream = (function() {
      function AudioStream(strFileName) {
        var _audioContext;
        this.strFileName = strFileName;
        _audioContext = window.AudioContext || window.webkitAudioContext;
        this._audioCore = new _audioContext();
        this._audioFilters = new AudioFilters(this._audioCore);
        this._boolLoading = false;
        this.boolPlaying = false;
        this.numPlayhead = 0;
        this._load();
      }


      /**
      		 * Resets the audiofilters on each stop as WebAudio does not allow reuse, hence we have to recreate on audio stop
       */

      AudioStream.prototype._reset = function() {
        if (this._audioBuffer) {
          this._audioFilters.setInput(this._audioBuffer);
          this._audioIn = this._audioFilters.getInput();
          this._audioOut = this._audioFilters.getOutput();
          return this._audioOut.connect(this._audioCore.destination);
        }
      };


      /**
      		 * Delegator to the AudioLoader, which gives back a success and failure callback
       */

      AudioStream.prototype._load = function() {
        this._boolLoading = true;
        return this._audioLoader = new AudioLoader(this.strFileName, this._audioCore).success((function(_this) {
          return function(_audioBuffer) {
            _this._audioBuffer = _audioBuffer;
            _this._reset();
            return _this._boolLoading = false;
          };
        })(this));
      };


      /**
      		 * Delegator to the Low filter available via AudioFilters
      		 * @param {Number} numValue Value between 40 and -40
       */

      AudioStream.prototype.setLow = function(numValue) {
        if (numValue !== void 0) {
          return this._audioFilters.setLowFilter(numValue);
        }
      };


      /**
      		 * Delegator to the Mid filter available via AudioFilters
      		 * @param {Number} numValue Value between 40 and -40
       */

      AudioStream.prototype.setMid = function(numValue) {
        if (numValue !== void 0) {
          return this._audioFilters.setMidFilter(numValue);
        }
      };


      /**
      		 * Delegator to the High filter available via AudioFilters
      		 * @param {Number} numValue Value between 40 and -40
       */

      AudioStream.prototype.setHigh = function(numValue) {
        if (numValue !== void 0) {
          return this._audioFilters.setHighFilter(numValue);
        }
      };


      /**
      		 * Delegator to the Volume available via AudioFilters
      		 * @param {Number} numValue Value between 0 and 1
       */

      AudioStream.prototype.setVolume = function(numValue) {
        if (numValue !== void 0) {
          return this._audioFilters.setVolume(numValue);
        }
      };


      /**
      		 * Delegator to the Pitch available via AudioFilters
      		 * @param {Number} numValue Value between -100 and 100 (%)
       */

      AudioStream.prototype.setPitch = function(numValue) {
        if (numValue !== void 0) {
          return this._audioFilters.setPitch(numValue);
        }
      };


      /**
      		 * Sets play to the audio object. Will try to use the saved playhead if nothing is filled in.
      		 * @param {Number} numPlayhead The point at which the song should start
       */

      AudioStream.prototype.setPlay = function(numPlayhead) {
        if (!this._boolLoading && !this.boolPlaying) {
          if (numPlayhead !== void 0) {
            this.numPlayhead = numPlayhead;
          }
          this._audioIn.start(this.numPlayhead);
          return this.boolPlaying = true;
        }
      };


      /**
      		 * Sets stop to the audio object. Will try saving the current playhead status when play is activated. Does a reset as required.
       */

      AudioStream.prototype.setStop = function() {
        if (!this._boolLoading && this.boolPlaying) {
          this.numPlayhead = this._audioOut.context.currentTime;
          this._audioIn.stop();
          this._reset();
          return this.boolPlaying = false;
        }
      };

      return AudioStream;

    })();
  });

}).call(this);
