// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {

    /**
    	 * Adds various filters to the audio source and auto chains them. It gives numerous options and exposes its in and output for usage.
    	 * At basic this function tries to support low, mid, hi, pitch and volume. These are basic channel filters.
     */
    var AudioFilters;
    return AudioFilters = (function() {
      function AudioFilters(_audioCore) {
        this._audioCore = _audioCore;
        this.numPitch = 0;
        this.numVolume = 1;
        this.numGain = 1;
        this.numLowFilter = 0;
        this.numMidFilter = 0;
        this.numHighFilter = 0;
      }


      /**
      		 * Sets all filters at once
      		 * @param {AudioBuffer} @_audioBuffer The input to be processed over multiple filters and nodes
       */

      AudioFilters.prototype.setInput = function(_audioBuffer) {
        this._audioBuffer = _audioBuffer;
        this._audioSrc = this._audioCore.createBufferSource();
        this._audioSrc.buffer = this._audioBuffer;
        if (this._audioSrc) {
          this._audioSrc.playbackRate.value = (100 + Number(this.numPitch)) / 100;
        }
        this._audioVolume = this._audioCore.createGain();
        this._audioVolume.gain.value = this.numVolume;
        this._audioGain = this._audioCore.createGain();
        this._audioGain.gain.value = this.numGain;
        this._audioLowFilter = this._audioCore.createBiquadFilter();
        this._audioLowFilter.type = 'lowshelf';
        this._audioLowFilter.frequency.value = 500;
        this._audioLowFilter.gain.value = this.numLowFilter;
        this._audioMidFilter = this._audioCore.createBiquadFilter();
        this._audioMidFilter.type = 'peaking';
        this._audioMidFilter.frequency.value = 750;
        this._audioMidFilter.gain.value = this.numMidFilter;
        this._audioHighFilter = this._audioCore.createBiquadFilter();
        this._audioHighFilter.type = 'highshelf';
        this._audioHighFilter.frequency.value = 1000;
        this._audioHighFilter.gain.value = this.numHighFilter;
        this._audioSrc.connect(this._audioGain);
        this._audioGain.connect(this._audioLowFilter);
        this._audioLowFilter.connect(this._audioMidFilter);
        this._audioMidFilter.connect(this._audioHighFilter);
        return this._audioHighFilter.connect(this._audioVolume);
      };


      /**
      		 * Returns the original input given in the constructor
      		 * @return {AudioBufferSource}
       */

      AudioFilters.prototype.getInput = function() {
        return this._audioSrc;
      };


      /**
      		 * Returns the last filter applied in the connect chain
      		 * @return {BiquadFilter}
       */

      AudioFilters.prototype.getOutput = function() {
        return this._audioVolume;
      };


      /**
      		 * Sets the gain for overdriving or lowering the general volume
      		 * @param {Number} @numGain Value between -40 and 40
       */

      AudioFilters.prototype.setGain = function(numGain) {
        this.numGain = numGain;
        if (this._audioGain) {
          return this._audioGain.gain.value = this.numGain;
        }
      };


      /**
      		 * Sets the low shelf filter
      		 * @param {Number} @numLowFilter Value between -40 and 40
       */

      AudioFilters.prototype.setLowFilter = function(numLowFilter) {
        this.numLowFilter = numLowFilter;
        if (this._audioLowFilter) {
          return this._audioLowFilter.gain.value = this.numLowFilter;
        }
      };


      /**
      		 * Sets the mid shelf filter
      		 * @param {Number} @numLowFilter Value between -40 and 40
       */

      AudioFilters.prototype.setMidFilter = function(numMidFilter) {
        this.numMidFilter = numMidFilter;
        if (this._audioMidFilter) {
          return this._audioMidFilter.gain.value = this.numMidFilter;
        }
      };


      /**
      		 * Sets the high shelf filter
      		 * @param {Number} @numLowFilter Value between -40 and 40
       */

      AudioFilters.prototype.setHighFilter = function(numHighFilter) {
        this.numHighFilter = numHighFilter;
        if (this._audioHighFilter) {
          return this._audioHighFilter.gain.value = this.numHighFilter;
        }
      };


      /**
      		 * Sets volume gain
      		 * @param {Number} @numVolume Value between 0 and 1
       */

      AudioFilters.prototype.setVolume = function(numVolume) {
        this.numVolume = numVolume;
        if (this._audioVolume) {
          return this._audioVolume.gain.value = this.numVolume;
        }
      };


      /**
      		 * Sets pitch in percentage relative to 100%
      		 * @param {Number} @numPitch Value between -100 and 100 (%)
       */

      AudioFilters.prototype.setPitch = function(numPitch) {
        this.numPitch = numPitch;
        if (this._audioSrc) {
          return this._audioSrc.playbackRate.value = (100 + Number(this.numPitch)) / 100;
        }
      };

      return AudioFilters;

    })();
  });

}).call(this);
